[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "geoalchemy2>=0.20.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-docx>=1.2.0",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]
